product = input()
price = int(input())
weight = int(input())
cash = int(input())
print("Чек")
print(f"{product} - {weight}кг - {price}руб/кг")
print(f"Итого: {price * weight}руб")
print(f"Внесено: {cash}руб")
print(f"Сдача: {cash - (price * weight)}руб")